[workspace]
members = [
  "query-planner-wasm",
  "harmonizer",
  "harmonizer-cli",
  "stargate",
  "stargate/crates/graphql-parser",
  "stargate/crates/query-planner",
  "stargate/crates/stargate-lib",
]
