# Unfortunately, GitHub Actions doesn't support YAML aliases OR depending
# on an Action from another Action, like other CI providers do.
#
# See https://github.com/actions/runner/issues/646#issuecomment-777325191
#
# To reduce subtle nuances and simplify a future where these can converge,
# please try to apply chances as equally as practical across these files!
# (At the time of this writing, uniform blocks are indicated with comments)
name: Rust Lint

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check_format_and_lint:
    continue-on-error: true # we want to show this check failure in GH but to not prevent building.
    name: Assert Format and Run Clippy
    runs-on: ubuntu-latest
    steps:
      ## Below this line to the designated comment is uniform across rust-test.yml, rust-slow-test.yml and lint.yml!
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy

      ### BUILD CACHE ###
      - name: Cache Cargo registry, target, index
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: linux-${{ steps.toolchain.outputs.rustc_hash }}-rust-${{ hashFiles('**/Cargo.lock') }}

      ### UP FROM HERE TO "Checkout Code" is  uniform in rust-test.yml, rust-slow-test.yml, and lint.yml!

      ### FORMATTING AND STYLE ###
      - name: Check formatting
        run: cargo fmt -- --check

      - name: Check Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
